### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by knownasilya**
Not sure why `test/fixtures/with_plugin_test.js` fails, returns a 404.. Any ideas?

### CODE REVIEW

**Comment by rstacruz** [comment]
thanks for looking into this! feel free to DM me on twitter or something :)

**Comment by rstacruz** [comment]
i've also no clue on why Travis fails with a 404... I'd love to know too.

**Comment by rstacruz** [comment]
I suspect this error from metalsmith-layouts is relevant:

```
 ✗ no files to process. See https://www.npmjs.com/package/metalsmith-layouts#no-files-to-process  
    at Ware.<anonymous> (/home/travis/build/rstacruz/metalsmith-start/node_modules/metalsmith-layouts/lib/index.js:143:12)  
    at Ware.<anonymous> (/home/travis/build/rstacruz/metalsmith-start/node_modules/wrap-fn/index.js:45:19)  
```

**Comment by rstacruz** [comment]
By the way, I've added you as a collaborator!

**Comment by knownasilya** [comment]
Thanks!

**Comment by sbrl** [comment]
Hey! Updating the dependencies is probably a good idea, because there's a vulnerability in `superstatic`, and a few other packages too!

Here's the output of `npm audit` for a test package that has only `metalsmith-start` as a dependency:

```
                      === npm audit security report ===                        
                                                                                
# Run  npm update connect --depth 3  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > superstatic > connect > debug             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > superstatic > connect > finalhandler >    │
│               │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > metalsmith > recursive-readdir >          │
│               │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > superstatic > minimatch                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > connect > debug                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > connect > finalhandler > debug            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > tiny-lr > body-parser > debug             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > tiny-lr > debug                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Path Traversal                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ superstatic                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > superstatic                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/652                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > observatory > lodash                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/577                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > superstatic > lodash                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/577                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ metalsmith-start                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ metalsmith-start > superstatic > nash > lodash               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/577                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 12 vulnerabilities (9 low, 3 high) in 1628 scanned packages
  run `npm audit fix` to fix 2 of them.
  10 vulnerabilities require manual review. See the full report for details.
```

**Comment by knownasilya** [comment]
Thanks, yeah this has been my motivation as well.

**Comment by sbrl** [comment]
Yay! Awesome. Will a new npm version be released, @knownasilya?

**Comment by knownasilya** [comment]
@sbrl not sure since I don't have npm rights for this repo. I opened an issue for @rstacruz

**Comment by sbrl** [comment]
Cool, thanks @knownasilya!

**Pull request merged**
